/* EDITING: each photo has its own position. x/y are percentages of its gallery;
   width/height are frame sizes in design pixels; rotation is degrees.
   gallery: 'opening' is the single right-hand collage.
   Change these values to move photos without moving text, sections or the ribbon.
   Optional crop: '50% 35%' changes the focal point inside the frame.
   cropBox: [left, top, width, height] selects a rectangle in source percentages.
   See README.md for examples and the gallery's page position. */
window.siteContent = {
  // Independent HTML fields for the two curved reading areas; no automatic copies.
  continuationCopy: [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sem neque, fermentum consequat tincidunt a, blandit vel ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. <br><br>Nullam vulputate ante in odio vestibulum consequat. Ut sed quam nec eros vestibulum imperdiet. In id porttitor elit. Integer eu est urna. Suspendisse laoreet facilisis tellus, at condimentum mauris malesuada vitae. Aenean elementum nunc nisl, et porta metus pretium at. Fusce id quam ullamcorper, tempor purus non, ullamcorper lorem. Duis et mollis sapien. Duis sed mauris et dui finibus condimentum. Integer sit amet risus nisl. Vestibulum id lectus pharetra, congue ligula vel, fringilla massa. Praesent orci ex, commodo ac feugiat vitae, congue id odio. Mauris pulvinar consequat aliquet. Etiam id ornare risus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sem neque, fermentum consequat tincidunt a, blandit vel ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. <br><br>Nullam vulputate ante in odio vestibulum consequat. Ut sed quam nec eros vestibulum imperdiet. In id porttitor elit. Integer eu est urna. Suspendisse laoreet facilisis tellus, at condimentum mauris malesuada vitae. Aenean elementum nunc nisl, et porta metus pretium at. Fusce id quam ullamcorper, tempor purus non, ullamcorper lorem. Duis et mollis sapien. Duis sed mauris et dui finibus condimentum. Integer sit amet risus nisl. Vestibulum id lectus pharetra, congue ligula vel, fringilla massa. Praesent orci ex, commodo ac feugiat vitae, congue id odio. Mauris pulvinar consequat aliquet. Etiam id ornare risus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sem neque, fermentum consequat tincidunt a, blandit vel ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. <br><br>Nullam vulputate ante in odio vestibulum consequat. Ut sed quam nec eros vestibulum imperdiet. In id porttitor elit. Integer eu est urna. Suspendisse laoreet facilisis tellus, at condimentum mauris malesuada vitae. Aenean elementum nunc nisl, et porta metus pretium at. Fusce id quam ullamcorper, tempor purus non, ullamcorper lorem. Duis et mollis sapien. Duis sed mauris et dui finibus condimentum. Integer sit amet risus nisl. Vestibulum id lectus pharetra, congue ligula vel, fringilla massa. Praesent orci ex, commodo ac feugiat vitae, congue id odio. Mauris pulvinar consequat aliquet. Etiam id ornare risus. ",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sem neque, fermentum consequat tincidunt a, blandit vel ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. <br><br>Nullam vulputate ante in odio vestibulum consequat. Ut sed quam nec eros vestibulum imperdiet. In id porttitor elit. Integer eu est urna. Suspendisse laoreet facilisis tellus, at condimentum mauris malesuada vitae. Aenean elementum nunc nisl, et porta metus pretium at. Fusce id quam ullamcorper, tempor purus non, ullamcorper lorem. Duis et mollis sapien. Duis sed mauris et dui finibus condimentum. Integer sit amet risus nisl. Vestibulum id lectus pharetra, congue ligula vel, fringilla massa. Praesent orci ex, commodo ac feugiat vitae, congue id odio. Mauris pulvinar consequat aliquet. Etiam id ornare risus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sem neque, fermentum consequat tincidunt a, blandit vel ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. <br><br>Nullam vulputate ante in odio vestibulum consequat. Ut sed quam nec eros vestibulum imperdiet. In id porttitor elit. Integer eu est urna. Suspendisse laoreet facilisis tellus, at condimentum mauris malesuada vitae. Aenean elementum nunc nisl, et porta metus pretium at. Fusce id quam ullamcorper, tempor purus non, ullamcorper lorem. Duis et mollis sapien. Duis sed mauris et dui finibus condimentum. Integer sit amet risus nisl. Vestibulum id lectus pharetra, congue ligula vel, fringilla massa. Praesent orci ex, commodo ac feugiat vitae, congue id odio. Mauris pulvinar consequat aliquet. Etiam id ornare risus. "],
  polaroids: [
    { id: 'loch', gallery: 'opening', src: 'assets/photos/IMG_1187.webp', alt: 'Hills and houses around a loch', x: 58, y: 1.81, width: 143, height: 169, rotation: 12 },
    { id: 'orange-hat', gallery: 'opening', src: 'assets/photos/IMG_0710.webp', alt: 'An orange top hat and heart-shaped glasses', x: 5, y: 7.11, width: 171, height: 205, rotation: 8, crop: '50% 28%' },
    { id: 'lighthouse', gallery: 'opening', src: 'assets/photos/IMG_1276.webp', alt: 'A lighthouse seen from the road', x: 62, y: 12.47, width: 164, height: 191, rotation: -6 },
    { id: 'window', gallery: 'opening', src: 'assets/photos/IMG_1808.webp', alt: 'An open window in a sunlit yellow building', x: 57, y: 24.94, width: 192, height: 210, rotation: 7 },
    { id: 'cliffs', gallery: 'opening', src: 'assets/photos/IMG_1544.webp', alt: 'Sunset above white cliffs', x: 64, y: 37.47, width: 162, height: 195, rotation: -10 },
    { id: 'life-chart', gallery: 'opening', src: 'assets/photos/IMG_1031.webp', alt: 'The hand-drawn SIRI LIFE chart', x: 8, y: 44.58, width: 300, height: 234, rotation: -4, cropBox: [15, 19, 74, 64], layer: 2 },
    { id: 'sunset', gallery: 'opening', src: 'assets/photos/IMG_1796.webp', alt: 'Photographing a sunset over fields', x: 51, y: 56.14, width: 215, height: 200, rotation: 7 },
    { id: 'dune', gallery: 'opening', src: 'assets/photos/IMG_1587.webp', alt: 'A game of Dune around the table', x: 8, y: 58.86, width: 190, height: 263, rotation: -8, cropBox: [13, 11, 81, 76] },
    { id: 'research', gallery: 'opening', src: 'assets/photos/IMG_1582.webp', alt: 'Presentation notes and a research paper on screen', x: 53, y: 68.67, width: 210, height: 190, rotation: -5 },
    { id: 'paint', gallery: 'opening', src: 'assets/photos/IMG_1657.webp', alt: 'Friends after a colourful afternoon', x: 3, y: 76.69, width: 280, height: 209, rotation: -6, cropBox: [11, 33, 83, 67], layer: 2 },
    { id: 'mirror', gallery: 'opening', src: 'assets/photos/IMG_1628.webp', alt: 'A selfie in an ornate museum mirror', x: 65, y: 79.34, width: 164, height: 200, rotation: 8, crop: '50% 35%' },
    { id: 'park', gallery: 'opening', src: 'assets/photos/IMG_1396.webp', alt: 'A group of friends beneath the trees', x: 12, y: 87.35, width: 300, height: 168, rotation: 4, cropBox: [12, 43, 68, 37], layer: 2 }
  ],
  collections: {
    home: { title: 'For <em>progeny</em> and <em>posterity.</em>', original: true },
    thousings: { title: '<em>Thousings.</em>', paragraphs: [], continuation: '' },
    musings: { title: 'A little <em>wondering.</em>', paragraphs: ['Listening to the world. Feeling the world. Enjoying the world’s many experiences, basking in the glory.'], continuation: 'Small <em>wonders.</em>' },
    tabsings: { title: 'One more <em>song.</em>', paragraphs: ['The songs that stay with us. The sun, the moon, the stars.'], continuation: 'Keep <em>listening.</em>' },
    ramblings: { title: 'A thought, then <em>another.</em>', paragraphs: ['For all the little things. For everything that doesn’t quite fit anywhere else.'], continuation: 'And <em>another.</em>' },
    vibesings: { title: 'Feeling the <em>world.</em>', paragraphs: ['Music, moments, and enjoying the world’s many experiences.'], continuation: 'Stay a <em>while.</em>' }
  }
};
