const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({ headless: true, channel: 'msedge' });
  const page = await browser.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.setViewportSize({width:1920,height:1080});
  await page.goto('http://127.0.0.1:4173');
  await page.evaluate(() => document.fonts.ready);
  await page.waitForFunction(() => document.querySelector('textPath')?.textContent.length > 50);
  assert.equal(await page.locator('[data-section="home"]').getAttribute('aria-current'), 'page');
  assert.equal(await page.locator('h1').evaluate(e => getComputedStyle(e).fontWeight), '500');
  assert.equal(await page.locator('h1 em').first().evaluate(e => getComputedStyle(e).fontWeight), '500');
  assert.match(await page.locator('.text-ribbon text').first().evaluate(e => getComputedStyle(e).fontFamily), /Source Code Pro/);
  assert.equal(await page.locator('.text-ribbon text').first().evaluate(e => getComputedStyle(e).fontWeight), '800');
  assert.equal(await page.evaluate(() => document.fonts.check('800 10px "Source Code Pro"')), true);
  assert.equal(await page.locator('.drop-cap').evaluate(e => getComputedStyle(e, '::first-letter').initialLetter), '2');
  await page.waitForFunction(()=>document.documentElement.dataset.ribbonReady==='true');
  const snapshotRibbon = () => page.locator('.text-ribbon').innerHTML();
  const homeRibbon = await snapshotRibbon();
  assert.equal(await page.locator('.text-ribbon linearGradient').count(), 0, 'Ribbon retains uniform colour');
  const headingBefore=await page.locator('h1').boundingBox();
  await page.evaluate(() => {
    const value = document.querySelector('.word-value');
    const word = value.parentElement;
    const style = () => {
      const css = getComputedStyle(value);
      return [css.fontFamily, css.fontSize, css.fontWeight, css.fontStyle, css.color, css.letterSpacing];
    };
    window.scrambleCheck = { length: value.textContent.length, style: style(), frames: [] };
    const observer = new MutationObserver(() => {
      if (word.classList.contains('is-glitching')) window.scrambleCheck.frames.push({text:value.textContent,length:value.textContent.length,style:style()});
      else if (window.scrambleCheck.frames.length) observer.disconnect();
    });
    observer.observe(value, {childList:true,subtree:true,characterData:true});
  });
  await page.waitForFunction(()=>document.querySelector('.glitch-word').classList.contains('is-glitching'));
  await page.waitForFunction(()=>document.querySelector('.word-value').textContent!=='posterity.');
  assert.match(await page.locator('.word-value').innerText(), /[!?<>/{}\[\]#%&*+_░]/, 'Scramble uses the full glitch character set');
  await page.waitForFunction(()=>!document.querySelector('.glitch-word').classList.contains('is-glitching'));
  const changedWord=await page.locator('.word-value').innerText();
  const scrambleCheck = await page.evaluate(() => window.scrambleCheck);
  assert.ok(scrambleCheck.frames.length >= 8, 'Observe multiple random-character frames');
  assert.match(scrambleCheck.frames.map(frame => frame.text).join(''), /[!?<>/{}\[\]#%&*+_]/, 'Light-shade blocks are mixed with the other glitch symbols');
  for (const frame of scrambleCheck.frames) {
    assert.equal(frame.length, scrambleCheck.length, 'Scramble keeps the outgoing word length');
    assert.deepEqual(frame.style, scrambleCheck.style, 'Scramble keeps the same font, size, weight and colour');
  }
  assert.ok(['posterity.','blog posts.','PB&J.','white girl pop.','percussion.','progress.','Prague.'].includes(changedWord));
  await page.waitForFunction(()=>!document.querySelector('.glitch-word').classList.contains('is-glitching'));
  assert.equal((await page.locator('h1').boundingBox()).height,headingBefore.height,'Word changes must not shift the layout');
  assert.deepEqual(await snapshotRibbon(),homeRibbon,'Heading animation must not shift ribbon');
  for (const section of ['thousings','musings','tabsings','ramblings','vibesings','home']) {
    await page.locator(`[data-section="${section}"]`).click();
    await page.waitForFunction(key => document.querySelector(`[data-section="${key}"]`).getAttribute('aria-current') === 'page', section);
    await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
    assert.deepEqual(await snapshotRibbon(), homeRibbon, `Ribbon stays fixed on ${section}`);
  }
  assert.equal(await page.locator('.scrapbook').isVisible(), true);
  await page.mouse.move(1200,100);
  await page.waitForTimeout(700);
  const stillFlower = await page.locator('[data-section="home"] .flower').evaluate(e => getComputedStyle(e).transform);
  await page.locator('[data-section="home"]').hover();
  await page.waitForTimeout(250);
  const rotatingFlower = await page.locator('[data-section="home"] .flower').evaluate(e => getComputedStyle(e).transform);
  await page.waitForTimeout(450);
  const rotatedFlower = await page.locator('[data-section="home"] .flower').evaluate(e => getComputedStyle(e).transform);
  assert.notEqual(stillFlower, rotatingFlower);
  assert.notEqual(rotatingFlower, rotatedFlower);
  await page.waitForTimeout(150);
  const finishedFlower = await page.locator('[data-section="home"] .flower').evaluate(e=>getComputedStyle(e).transform);
  await page.mouse.move(1200,100);
  await page.waitForTimeout(100);
  assert.equal(await page.locator('[data-section="home"] .flower').evaluate(e=>getComputedStyle(e).transform), finishedFlower, 'Leaving the flower must not start a reverse spin');
  assert.equal(await page.locator('[data-section="home"] .flower').evaluate(e=>e.getAnimations().length),0);
  await page.emulateMedia({reducedMotion:'reduce'});
  assert.equal(await page.locator('[data-section="home"] .flower').evaluate(e=>getComputedStyle(e).transitionDuration),'0s');
  await page.emulateMedia({reducedMotion:'no-preference'});
  await page.locator('.sidebar .brand').hover();
  await page.waitForFunction(() => getComputedStyle(document.querySelector('.sidebar .logo-orange')).opacity === '1');
  assert.equal(await page.locator('.sidebar .logo-orange').evaluate(e => getComputedStyle(e).opacity), '1');
  await page.locator('[data-section="musings"]').click();
  await page.waitForFunction(() => getComputedStyle(document.querySelector('[data-section="musings"] .flower')).opacity === '1');
  assert.equal(await page.locator('[data-section="musings"]').getAttribute('aria-current'), 'page');
  assert.match(await page.locator('h1').innerText(), /wondering/);
  assert.equal(await page.locator('[data-section="musings"] .flower').evaluate(e => getComputedStyle(e).opacity), '1');
  await page.locator('.sidebar .brand').click();
  await page.waitForURL(url=>url.hash==='#home');
  assert.ok(page.url().endsWith('#home'), 'Sidebar logo returns Home');
  await page.waitForFunction(() => document.documentElement.classList.contains('site-ready'));
  assert.match(await page.locator('h1').innerText(), /progeny/);
  const before = await page.locator('.sidebar').boundingBox();
  await page.evaluate(() => window.scrollTo(0, 1500));
  await page.waitForTimeout(500);
  const after = await page.locator('.sidebar').boundingBox();
  assert.equal(before.y, after.y);
  assert.equal(before.x, after.x);

  await page.locator('.polaroid-film button').click();
  await page.waitForFunction(()=>document.querySelector('.media-dialog video')?.readyState >= 2);
  assert.equal(await page.locator('.media-dialog video').evaluate(e=>e.controls),true);
  await page.locator('.media-dialog video').evaluate(e=>e.play());
  assert.equal(await page.locator('.media-dialog video').evaluate(e=>e.paused),false);
  await page.keyboard.press('Escape');
  await page.waitForFunction(()=>!document.querySelector('.media-dialog video'));
  await page.locator('.polaroid:not(.polaroid-film) button').first().click();
  assert.equal(await page.locator('.media-dialog img').getAttribute('src'),'assets/moments/img_1808.jpg');
  await page.getByRole('button',{name:'Close media'}).click();
  assert.deepEqual(errors,[]);
  console.log('PASS: desktop/phone layouts, Source Code Pro ExtraBold, uniform ribbon width and colour, mixed-symbol glitch without layout shifts, stable ribbon across collections, one-way flower spin, reduced motion, logo Home navigation, image/video playback.');
  await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
